guardian/gibbons

- src/main/scala/com.gu.gibbons/config/Settings.scala
- src/main/scala/com.gu.gibbons/lambdas/UserDidNotAnswerLambda.scala
- src/main/scala/com.gu.gibbons/lambdas/UserReminderLambda.scala
- src/test/scala/com.gu.bonobo/config/SettingsSpec.scala
This project provides a good ground to flesh out a few ideas I have around how we should write code moving forward, but with timing constraints I have neglected a few areas and want to set the records straight. First in line is narrowing the trusted code area as much as possible, and it makes sense to start at the end of the world, in particular the program's inputs.
In this PR, the reading of program's settings is made more resilient.
- using applicative style and cats' `ValidatedNel`, we can report all errors at once, if any
- `Regions.fromName` can throw (even though it is not documented), so we make sure to catch that
- unit tests to seal the deal
> Parsing settings

- cloudformation.yaml
- src/main/scala/com.gu.gibbons/UserDidNotAnswer.scala
- src/main/scala/com.gu.gibbons/UserReminder.scala
- src/main/scala/com.gu.gibbons/config/Settings.scala
- src/main/scala/com.gu.gibbons/lambdas/UserReminderLambda.scala
- src/main/scala/com.gu.gibbons/model/Json.scala
- src/main/scala/com.gu.gibbons/model/Result.scala
- src/main/scala/com.gu.gibbons/model/UrlGenerator.scala
- src/main/scala/com.gu.gibbons/model/bonobo.scala
- src/main/scala/com.gu.gibbons/services/BonoboService.scala
- src/main/scala/com.gu.gibbons/services/interpreters/BonoboInterpreter.scala
- src/test/scala/com.gu.bonobo/UserReminderSpec.scala
- src/test/scala/com.gu.bonobo/config/SettingsSpec.scala
- src/test/scala/com.gu.bonobo/services/interpreters.scala
- src/test/scala/com.gu.bonobo/services/package.scala
We don't want to mistakenly get internal/external/rights managed keys deleted because the email address of their respective user account is not checked or does not exist anymore -- we'll deal with these keys offline.
As a result, gibbons is updated to notify only Developer accounts. This introduces a small difficulty in that the tier is a property of a key, not of a user. So we must first query keys and then only retrieve the corresponding user accounts. Then it's business as usual.
> Notify only users who own Developer keys

- src/main/scala/com.gu.gibbons/UserDidNotAnswer.scala
No more emails are sent out to non-Developer accounts; here we make sure the cleanup process does the same.
> Double-check cleaned up accounts are developer accounts

- src/main/scala/com.gu.gibbons/services/interpreters/BonoboInterpreter.scala
Unless you thoroughly read the JavaDoc, OkHttp will only let you know that it's leaking resources by issuing warnings through its own logger.
It turns out not closing responses can exhaust the thread pool allocated to the client and ultimately shut down the whole application.
Here I'm just making sure the resource is cleaned up no matter the outcome of the computation.
> Cleanup OkHttp resources when done

- .gitignore
- cloudformation.yaml
Postpones invocation of `DidNotAnswerLambda`. See in-line comments for context.
> Postpone DidNotAnswerLambda invocation

- cloudformation.yaml
Now that we have changed the tier of Developer keys used by services, we can re-enable the lambda which deletes keys under the developer tier.
> Re-enable did not answer lambda

- src/main/scala/com.gu.gibbons/services/BonoboService.scala
The oldEnough function appears to to deprecated and uncalled. The actual selection for delete occurs in the database query?
Removing so future devs don't see it and assume this is the actual logic.
> Delete unused oldEnough function

- README.md
- cloudformation.yaml
Prevent the cleanup schedule running. For a LONG time. This is so we can double-check that the key cleansing process is working as expected.
Deploy. The reminder lambda should run but the clean-up one shouldn't.
No more keys are deleted for a while.
Risks are minimal. Dormant keys may stick around longer than we'd like but will be swept away when we enable the lambda again.
N/A
N/A
> Postpone auto-cleanup lambda temporarily. And ADD A README!

- src/main/twirl/deleted.scala.html
- src/main/twirl/reminder.scala.html
Updates the email copy sent to users to inform them their keys have been deleted, as it incorrectly stated that keys get deleted when they are not used for 30 months, when in fact they get deleted if the user does not respond to the key extension email, regardless of whether they use their key(s) or not.
Change is pretty straightforward, there is probably no need to test it unless you really want to :D 
In which case, you can try creating a key and manually changing the creation date to an old date, then wait for the email lambda to run (it does every 24 hours), or attempt to run the lambda manually. (If you think there is a better way to test this -which there probably is- please feel free to suggest.)
> Updating inaccurate copy for key deletion email

- README.md
- cloudformation.yaml
- src/main/scala/com.gu.gibbons/Script.scala
- src/main/scala/com.gu.gibbons/config/Settings.scala
- src/main/scala/com.gu.gibbons/lambdas/GenericLambda.scala
- src/test/scala/com.gu.bonobo/UserReminderSpec.scala
- src/test/scala/com.gu.bonobo/config/SettingsSpec.scala
This changes dryRun parameter to be set as an environment variable rather than as a lambda event input. This is to avoid the need to cloudform whenever we want to run in dry mode.
You can set the DRY_RUN environment variable in the AWS lambda(s). Upon invoking the lambda, you should be able to see a message in the logs that specifies which mode Gibbons is running in.
We should be able to run Gibbons in dry mode and find the information we need about the "would be reminded/deleted" users in the logs
This is a relatively low risk change as it does not change any key-handling logic
> Change dryRun settings to environment variable

- src/main/scala/com.gu.gibbons/UserReminder.scala
- src/main/scala/com.gu.gibbons/services/interpreters/BonoboInterpreter.scala
Gibbons was deleting non-developer keys due to the fact that it would delete any users who own developer keys regardless of whether they own other keys or not. This PR updates the function that filters the users who we need to notify/delete.
Can run in dry mode and confirm the list of users to be deleted does not include non-dev key owners
No more complaints regarding non-developer keys gone missing.
This is a risky change as we could end up deleting the wrong users/keys if the function does not work as we intend it to.
> Keep non developers

- cloudformation.yaml
Re-enables the Gibbons cleanup lambda. Both Gibbons lambdas have been set to run in Dry Mode in AWS, so this should be a low-risk change.
> re-enabling gibbons cleanup lambda

- src/main/scala/com.gu.gibbons/Script.scala
- src/main/scala/com.gu.gibbons/UserDidNotAnswer.scala
- src/main/scala/com.gu.gibbons/UserReminder.scala
- src/main/scala/com.gu.gibbons/model/bonobo.scala
- src/main/scala/com.gu.gibbons/model/package.scala
- src/main/scala/com.gu.gibbons/services/BonoboService.scala
- src/main/scala/com.gu.gibbons/services/EmailService.scala
- src/main/scala/com.gu.gibbons/services/interpreters/BonoboInterpreter.scala
- src/main/scala/com.gu.gibbons/services/interpreters/EmailInterpreter.scala
- src/main/scala/com.gu.gibbons/utils/UrlGenerator.scala
- src/main/twirl/deleted.scala.html
- src/main/twirl/reminder.scala.html
- src/test/scala/com.gu.bonobo/UserReminderSpec.scala
- src/test/scala/com.gu.bonobo/services/interpreters.scala
- src/test/scala/com.gu.bonobo/services/package.scala
This moves the developer key extension/deletion logic from the User level to the Key level. This was done to avoid deleting a user and all their keys. Once a user doesn't have any keys left they will be deleted automatically. The user deletion logic has been moved from Gibbons to Bonobo.
To be end-to-end tested on CODE
Users should be able to extend/delete their developer keys.
This is a major change to the way we handle key cleanup logic, so we need to make sure we didn't break anything.
> New key cleanup logic

- src/main/scala/com.gu.gibbons/UserDidNotAnswer.scala
Fixes a bug where we were attempting to retrieve the key's owner after deleting the key. We need to know the key owner so that we could notify them that their key has been deleted. Our failure to get the key owner was throwing an exception meaning the users who ignored the reminders weren't being notified that their keys were deleted. I switched the order to get the key owner and THEN delete the key.
This needs to be tested on PROD (as our CODE environment doesn't send emails), however it wouldn't break anything even in the event that the fix doesn't work.
Clean up lambda should send deletion emails successfully.
This is a low risk change.
> Fix bug in key deletion email

- project/Dependencies.scala
This bumps the log4j version to latest "2.15.0", as well as lambdalog4j to version "1.3.0" as per AWS guidance here:
https://aws.amazon.com/security/security-bulletins/AWS-2021-005/
These changes are required to mitigate an RCE exploit found in log4j. More details here:
https://www.lunasec.io/docs/blog/log4j-zero-day/#how-the-exploit-works
> Bumping log4j and lambdalog4j

- project/Dependencies.scala
[## Describe your changes
We're bumping `log4j` to `2.16.0` and `lambda log4j` to `1.4.0`
* What has changed
* `dependencies.scala`
* Why is this change required
* Security patches
This change 
impact the CAPI data model
This change can be tracked on a dashboard
If it's not obvious, consider adding a screenshot showing what to look out for on the graph/dashboard
Tests have been run on 
This is really useful to help someone understand the scope of the change and, perhaps more importantly, rollback 
considerations you've thought about in case something goes wrong.
Say as much as possible about internal and external dependencies that might be impacted by this change.
Please give a brief assessment here
If there were significant issues we'd expect problems during the build process. That was …
> bump log4j and lambda log4j

- src/main/scala/com.gu.gibbons/UserDidNotAnswer.scala
This temporarily disables sending key deletion emails to users in attempt to reduce the amount of spam complaints 
Tested on CODE but as our CODE environment doesn't send emails, we would need to deploy to PROD and monitor.
We need to monitor the percentage of complaints we get with AWS and see improvements.
This is a low-risk change.
> Temporarily disable key deletion emails

- riff-raff.yaml
Using `bucketssmlookup` to true instead of explicit bucket name inside riffraff file. recommended by DevX team.
To fix deploy warning as shown in screenshot below :
Tested on CODE deployment and result is now no warnings on the page, as shown in screenshot below:
> To use bucketssmslookup in riffraff 

- .github/workflows/build.yml
- build.sbt
- cloudformation.yaml
- project/build.properties
- project/plugins.sbt
Nudge build and runtime to Java 11.
We want to remove occurrences of projects which require developers to maintain a Java 8 stack to work with them.
Trigger dry runs of CODE lambdas.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> Java 11 build and runtime

- src/main/scala/com.gu.gibbons/config/Settings.scala
- src/main/twirl/deleted.scala.html
- src/main/twirl/reminder.scala.html
Syndication have asked us to decrease developer key inactivity period from 30 months to 3 months. If introduced immediately, this change will result in over 15k keys "in debt", which will be challenging to process and send emails to. 
This change proposes decreasing that inactivity period gradually over the course of the next month. Which will only add to Gibbons the burden of one month worth of keys at a time.
Can be tested in DRY_RUN.
> Gradually decrease inactivity period

- project/plugins.sbt
Although present in the initial commit of this project (ee4465c31efe66bb613d802e3e9a385a8fb46710), I don't think this repo has ever publish Maven artifacts, and so doesn't need the `sbt-release` plugin?
> Remove unused `sbt-release` plugin
